### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by Raizo62** [realvitya/clicol#13]
Hi

On your README, you say that python2 is necessary.

I have installed and tested clicol with python3 (i need python3, and python2 goes to his end of life).

clicol (telnet) seems to work correctly with python3. What is the problem ?

Why will you not use python 3 ?

**Comment by realvitya** [comment]
Hey,
Sorry, I meant 2.6+ as bare minimum. It took a lot of effort to migrate the code to be "bilingual". So it should run in python 3. I should clarify in README then...

**Comment by realvitya** [comment]
just updated the README...

**Comment by Raizo62** [comment]
Great :-)
Thanks
