### ISSUE TITLE
completion is slower with new patch (frozenset)

### ISSUE THREAD

**Issue by Raizo62** [realvitya/clicol#20]
Hi

On some cisco, the completion is slower with the new patch (frozenset)

For example, with the command "show ip i" : 
- with the old version : after tab, it instantly displays a new line with "show ip i"
- with the new version : after tab, it displays a new line with "show i" (sometimes "show" or "show i" or ""), waits 1 or 2 seconds before to display "show ip i"

In this [clicol_log.txt](https://github.com/realvitya/clicol/files/7072302/clicol_log.txt), the 1 or 2 seconds is after "EFFECTS-interactive: False / {'paste_error'}"

**Comment by realvitya** [comment]
Hi Raizo,
sorry for that. I reverted the latest commit. I haven't experienced your problem and was using this patch since a while.
